#= require jquery
#= require jquery_ujs
#= require jquery.ui.datepicker
#= require jquery.ui.autocomplete
#= require moment
#= require underscore
#= require backbone
#= require hamlcoffee
#= require_self
#= require inventory
#= require_tree ../templates
#= require_tree ./models
#= require_tree ./collections
#= require_tree ./views
#= require_tree ./routers
